= karajo changelog

== karajo v0.2.0 (2021-12-07)

===  Breaking changes

*  all: move the karajo web user interface to sub-directory karajo

   In case the user of karajo module also have embedded memfs, merging
   the Karajo memfs with their memfs may cause conflict (especially if
   the user have /index.html and /favicon.png).

===  Enhancements

*  www: make the showAttrs and showLogs to pool per 10 seconds

   Previously, the showAttrs and showLogs pool the job attributes and logs
   per job interval. For example, if the interval is 5 minutes, then the
   attributes and/or logs will be refreshed every 5 minutes.

   In order to make user can view the latest attributes and/logs
   immediately, we changes the interval to 10 seconds.

===  Chores

*  all: add prefix "http://" to address when logging at Start


== karajo v0.1.0 (2021-06-05)

The first release of karajo, programmable HTTP workers with web interface.

Features,

* Running job on specific interval
* Preserve the job states on restart
* Able to pause and resume specific job
* HTTP APIs to programmatically interact with karajo
